# -*- encoding: utf-8 -*-

=begin
#QuantumDMN Ruby SDK

#API for the QuantumDMN platform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "quantumdmn/version"

Gem::Specification.new do |s|
  s.name        = "quantumdmn-sdk"
  s.version     = Quantumdmn::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["QuantumDMN"]
  s.email       = ["support@quantumdmn.com"]
  s.homepage    = "https://quantumdmn.com"
  s.summary     = "QuantumDMN Ruby SDK"
  s.description = "API for the QuantumDMN platform."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'jwt', '~> 2.7'
  s.add_runtime_dependency 'ostruct'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? && !f.end_with?('.gem') }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
