=begin
#Go DMN Web API

#API for the Go DMN Web application.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Quantumdmn::BatchEvaluateDesignRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Quantumdmn::BatchEvaluateDesignRequest do
  #let(:instance) { Quantumdmn::BatchEvaluateDesignRequest.new }

  describe 'test an instance of BatchEvaluateDesignRequest' do
    it 'should create an instance of BatchEvaluateDesignRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Quantumdmn::BatchEvaluateDesignRequest)
    end
  end

  describe 'test attribute "xml"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "inputs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
