=begin
#Go DMN Web API

#API for the Go DMN Web application.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Quantumdmn::EvaluateDesignRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Quantumdmn::EvaluateDesignRequest do
  #let(:instance) { Quantumdmn::EvaluateDesignRequest.new }

  describe 'test an instance of EvaluateDesignRequest' do
    it 'should create an instance of EvaluateDesignRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Quantumdmn::EvaluateDesignRequest)
    end
  end

  describe 'test attribute "xml"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "context"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "decision_services"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "decisions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
