=begin
#Go DMN Web API

#API for the Go DMN Web application.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Quantumdmn::GetVersion200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Quantumdmn::GetVersion200Response do
  #let(:instance) { Quantumdmn::GetVersion200Response.new }

  describe 'test an instance of GetVersion200Response' do
    it 'should create an instance of GetVersion200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Quantumdmn::GetVersion200Response)
    end
  end

  describe 'test attribute "version"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "build_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "commit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
