=begin
#Go DMN Web API

#API for the Go DMN Web application.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Quantumdmn::OverviewResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Quantumdmn::OverviewResponse do
  #let(:instance) { Quantumdmn::OverviewResponse.new }

  describe 'test an instance of OverviewResponse' do
    it 'should create an instance of OverviewResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Quantumdmn::OverviewResponse)
    end
  end

  describe 'test attribute "stats"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
