=begin
#Go DMN Web API

#API for the Go DMN Web application.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

# Common files
require 'quantumdmn/api_client'
require 'quantumdmn/api_error'
require 'quantumdmn/api_model_base'
require 'quantumdmn/version'
require 'quantumdmn/configuration'

# custom classes
require 'quantumdmn/zitadel_auth'
require 'quantumdmn/dmn_engine'

# Models
require 'quantumdmn/models/add_project_member_request'
require 'quantumdmn/models/batch_evaluate_design_request'
require 'quantumdmn/models/batch_evaluation_response'
require 'quantumdmn/models/batch_evaluation_response_results_inner'
require 'quantumdmn/models/batch_get_users_request'
require 'quantumdmn/models/create_definition_request'
require 'quantumdmn/models/create_project_request'
require 'quantumdmn/models/create_subscription_upgrade_transaction200_response'
require 'quantumdmn/models/create_subscription_upgrade_transaction_request'
require 'quantumdmn/models/credits_quota'
require 'quantumdmn/models/daily_stat'
require 'quantumdmn/models/definition'
require 'quantumdmn/models/definitions_quota'
require 'quantumdmn/models/error'
require 'quantumdmn/models/evaluate_design_request'
require 'quantumdmn/models/evaluate_design_request_kpi_initial_state_value_inner'
require 'quantumdmn/models/evaluate_design_request_kpi_initial_state_value_inner_metrics_inner'
require 'quantumdmn/models/evaluate_stored_request'
require 'quantumdmn/models/evaluation_result'
require 'quantumdmn/models/execution'
require 'quantumdmn/models/feel_value'
require 'quantumdmn/models/frontend_config'
require 'quantumdmn/models/frontend_config_oidc'
require 'quantumdmn/models/frontend_config_paddle'
require 'quantumdmn/models/get_customer_portal_session200_response'
require 'quantumdmn/models/get_health200_response'
require 'quantumdmn/models/get_version200_response'
require 'quantumdmn/models/hit_rule'
require 'quantumdmn/models/kpi_trend'
require 'quantumdmn/models/kpi_trend_data_inner'
require 'quantumdmn/models/organization_user'
require 'quantumdmn/models/overview_response'
require 'quantumdmn/models/overview_response_stats'
require 'quantumdmn/models/paginated_definitions_response'
require 'quantumdmn/models/paginated_executions_response'
require 'quantumdmn/models/pagination_metadata'
require 'quantumdmn/models/project'
require 'quantumdmn/models/project_member'
require 'quantumdmn/models/project_permissions'
require 'quantumdmn/models/project_usage'
require 'quantumdmn/models/quota'
require 'quantumdmn/models/quota_item'
require 'quantumdmn/models/simulation_request'
require 'quantumdmn/models/simulation_response'
require 'quantumdmn/models/simulation_response_results_inner'
require 'quantumdmn/models/tier'
require 'quantumdmn/models/tier_features_config'
require 'quantumdmn/models/tier_limits'
require 'quantumdmn/models/update_customer_settings_request'
require 'quantumdmn/models/update_definition_request'
require 'quantumdmn/models/update_project_member_role_request'
require 'quantumdmn/models/user_permissions'

# APIs
require 'quantumdmn/api/default_api'

module Quantumdmn
  class << self
    # Customize default settings for the SDK using block.
    #   Quantumdmn.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
