=begin
#Go DMN Web API

#API for the Go DMN Web application.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module Quantumdmn
  class Execution < ApiModelBase
    attr_accessor :id

    attr_accessor :definition_id

    attr_accessor :executed_at

    attr_accessor :executed_by

    attr_accessor :inputs

    attr_accessor :outputs

    attr_accessor :xml_definition_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'definition_id' => :'definition_id',
        :'executed_at' => :'executed_at',
        :'executed_by' => :'executed_by',
        :'inputs' => :'inputs',
        :'outputs' => :'outputs',
        :'xml_definition_id' => :'xml_definition_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'definition_id' => :'String',
        :'executed_at' => :'Time',
        :'executed_by' => :'String',
        :'inputs' => :'Hash<String, FeelValue>',
        :'outputs' => :'FeelValue',
        :'xml_definition_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'outputs',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Quantumdmn::Execution` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Quantumdmn::Execution`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'definition_id')
        self.definition_id = attributes[:'definition_id']
      else
        self.definition_id = nil
      end

      if attributes.key?(:'executed_at')
        self.executed_at = attributes[:'executed_at']
      else
        self.executed_at = nil
      end

      if attributes.key?(:'executed_by')
        self.executed_by = attributes[:'executed_by']
      end

      if attributes.key?(:'inputs')
        if (value = attributes[:'inputs']).is_a?(Hash)
          self.inputs = value
        end
      else
        self.inputs = nil
      end

      if attributes.key?(:'outputs')
        self.outputs = attributes[:'outputs']
      else
        self.outputs = nil
      end

      if attributes.key?(:'xml_definition_id')
        self.xml_definition_id = attributes[:'xml_definition_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @definition_id.nil?
        invalid_properties.push('invalid value for "definition_id", definition_id cannot be nil.')
      end

      if @executed_at.nil?
        invalid_properties.push('invalid value for "executed_at", executed_at cannot be nil.')
      end

      if @inputs.nil?
        invalid_properties.push('invalid value for "inputs", inputs cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @definition_id.nil?
      return false if @executed_at.nil?
      return false if @inputs.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] definition_id Value to be assigned
    def definition_id=(definition_id)
      if definition_id.nil?
        fail ArgumentError, 'definition_id cannot be nil'
      end

      @definition_id = definition_id
    end

    # Custom attribute writer method with validation
    # @param [Object] executed_at Value to be assigned
    def executed_at=(executed_at)
      if executed_at.nil?
        fail ArgumentError, 'executed_at cannot be nil'
      end

      @executed_at = executed_at
    end

    # Custom attribute writer method with validation
    # @param [Object] inputs Value to be assigned
    def inputs=(inputs)
      if inputs.nil?
        fail ArgumentError, 'inputs cannot be nil'
      end

      @inputs = inputs
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          definition_id == o.definition_id &&
          executed_at == o.executed_at &&
          executed_by == o.executed_by &&
          inputs == o.inputs &&
          outputs == o.outputs &&
          xml_definition_id == o.xml_definition_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, definition_id, executed_at, executed_by, inputs, outputs, xml_definition_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
