=begin
#Go DMN Web API

#API for the Go DMN Web application.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0-SNAPSHOT

=end

require 'date'
require 'time'

module Quantumdmn
  class OverviewResponseStats < ApiModelBase
    attr_accessor :total_requests

    attr_accessor :total_credits

    attr_accessor :requests_trend

    attr_accessor :credits_trend

    attr_accessor :kpi_trends

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'total_requests' => :'totalRequests',
        :'total_credits' => :'totalCredits',
        :'requests_trend' => :'requestsTrend',
        :'credits_trend' => :'creditsTrend',
        :'kpi_trends' => :'kpiTrends'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'total_requests' => :'Integer',
        :'total_credits' => :'Integer',
        :'requests_trend' => :'Array<DailyStat>',
        :'credits_trend' => :'Array<DailyStat>',
        :'kpi_trends' => :'Array<KpiTrend>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Quantumdmn::OverviewResponseStats` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Quantumdmn::OverviewResponseStats`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'total_requests')
        self.total_requests = attributes[:'total_requests']
      end

      if attributes.key?(:'total_credits')
        self.total_credits = attributes[:'total_credits']
      end

      if attributes.key?(:'requests_trend')
        if (value = attributes[:'requests_trend']).is_a?(Array)
          self.requests_trend = value
        end
      end

      if attributes.key?(:'credits_trend')
        if (value = attributes[:'credits_trend']).is_a?(Array)
          self.credits_trend = value
        end
      end

      if attributes.key?(:'kpi_trends')
        if (value = attributes[:'kpi_trends']).is_a?(Array)
          self.kpi_trends = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          total_requests == o.total_requests &&
          total_credits == o.total_credits &&
          requests_trend == o.requests_trend &&
          credits_trend == o.credits_trend &&
          kpi_trends == o.kpi_trends
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [total_requests, total_credits, requests_trend, credits_trend, kpi_trends].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
